In [41]:
import numpy as np
l1 = [1,6,8,9,3]
array1 = np.array(l1)
array1

array([1, 6, 8, 9, 3])

In [42]:
array1.size

5

In [43]:
array1.shape

(5,)

In [44]:
array2 = np.array([[1,2,3,4,56],[8,5,3,9,10]])
array2[0]

array([ 1,  2,  3,  4, 56])

In [17]:
array2[1]

array([ 8,  5,  3,  9, 10])

In [45]:
array2[0:2, 3:]

array([[ 4, 56],
       [ 9, 10]])

In [46]:
copy_array2 = array2

In [23]:
copy_array2[0,0] = 900

In [24]:
copy_array2

array([[900,   2,   3,   4,  56],
       [  8,   5,   3,   9,  10]])

In [25]:
array2

array([[900,   2,   3,   4,  56],
       [  8,   5,   3,   9,  10]])

In [47]:
copy_array2 = array2.copy()

In [48]:
copy_array2[1,1] = 8976

In [49]:
copy_array2

array([[   1,    2,    3,    4,   56],
       [   8, 8976,    3,    9,   10]])